((:interfaces
  (:admin . "r-simple-admin")
  (:auth . "r-simple-auth")
  (:ban . "r-simple-ban")
  (:cache . "r-simple-cache")
  (:data-model . "r-simple-model")
  (:database . "i-lambdalite")
  (:relational-database . "i-sqlite")
  (:logger . "i-verbose")
  (:mail . "i-smtp")
  (:profile . "r-simple-profile")
  (:rate . "r-simple-rate")
  (:server . "i-hunchentoot")
  (:session . "r-simple-sessions")
  (:user . "r-simple-users"))
 (:domains . ("radiance" "localhost"))
 (:startup :r-welcome :r-simple-errors)
 (:routes)
 (:debugger . :if-swank-connected))
